### ISSUE TITLE
Remove Visual Studio / GitHub Actions workaround

### ISSUE THREAD

**Issue by sudara** [sudara/pamplejuce#103]
The following was added to the GitHub Workflow configure step:

`-DCMAKE_CXX_FLAGS="/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR"`

This is because they broke all C++ builds, basically. See:

https://github.com/actions/runner-images/issues/10004

This issue is a reminder to check if it needs to be removed, perhaps late June or early July (unless GA is really on top of it)

**Comment by zsliu98** [comment]
It seems that the fix (image 20240610.1) will complete its deployment very soon. I have just checked my repo and it has already been deployed.

https://github.com/actions/runner-images

BTW, will you go back to Clang on Windows?

**Comment by sudara** [comment]
Ah thanks for the heads up. I wonder what "deploying" should mean and if I should already revert.

I sort of like MSVC on Windows in the end. It's fast and there have been several problems with Clang... Maybe a good argument is that clang on windows is a niche of a niche (C++ compilation on GitHub Actions) so won't be supported as solidly as MSVC?...

**Comment by zsliu98** [comment]
> Ah thanks for the heads up. I wonder what "deploying" should mean and if I should already revert.
> 
> I sort of like MSVC on Windows in the end. It's fast and there have been several problems with Clang... Maybe a good argument is that clang on windows is a niche of a niche (C++ compilation on GitHub Actions) so won't be supported as solidly as MSVC?...

~I think it will finish the deployment very soon~ It has been fully deployed (seems to be much more responsive than the previous Linux one). And thanks for your opinion on MSVC. I will try it out soon.
