### ISSUE TITLE
setting up code signing

### ISSUE THREAD

**Issue by davispolito** [sudara/pamplejuce#128]
i dont know if this is the best place to ask. I am wondering how the code signing works. 

I see several secrets related to code signing but am unsure how that gets set up. 

[this repo](https://github.com/Apple-Actions/import-codesign-certs
)

seems to imply i can load up all my certs into one p12 file and upload as a single secret. You use several secrets 
secrets.DEV_ID_APP_CERT
 secrets.DEVELOPER_ID_APPLICATION
 secrets.NOTARIZATION_USERNAME
secrets.TEAM_ID

are these all individual secrets you upload as well? 

What is the difference between DEV_ID_APP_CERT and DEVELOPER_ID_APPLICATION

**Comment by sudara** [comment]
Howdy!

The cert is just one secret needed.

Check out https://melatonin.dev/blog/how-to-code-sign-and-notarize-macos-audio-plugins-in-ci/ for all the details.

I'll be moving Pamplejuce to https://github.com/sudara/basic-macos-keychain-action which replaces that other action, but the things you provide will be the same (it's just more transparent and self-hosted friendly too).

**Comment by davispolito** [comment]
you rock!
