### ISSUE TITLE
Artifact names wrong

### ISSUE THREAD

**Issue by jacobweber** [sudara/pamplejuce#13]
The `upload-artifact` steps have `name: ${{ env.PRODUCT_NAME }}.zip` etc.

But the `action-gh-release` step fails to find them, because it has `${{ env.PROJECT_NAME }}-Linux.zip/*` (PROJECT vs PRODUCT.)

Personally I prefer PRODUCT, since it puts the version number in the filename. Something like `${{ env.PROJECT_NAME }}-*-Linux.zip/*` seems to work.

**Comment by sudara** [comment]
Thanks for catching this, I merged the `codesign` branch prematurely, never actually tried to push a tag :) I'll get it cleaned up!
