### ISSUE TITLE
GH workflow error: `fatal error: 'curl/curl.h' file not found`

### ISSUE THREAD

**Issue by hugofloresgarcia** [sudara/pamplejuce#17]
Hi! When building a plugin with `JUCE_USE_CURL=1` and `NEEDS_CURL TRUE`, I run into the following error when building for Linux in GH actions:
```
/home/runner/work/tensorjuce-wave-to-wave/tensorjuce-wave-to-wave/JUCE/modules/juce_core/juce_core.cpp:92:13: fatal error: 'curl/curl.h' file not found
   #include <curl/curl.h>

```
Any help would be appreciated! Thanks :)

**Comment by sudara** [comment]
👋

You'll need to add `libcurl4-openssl-dev` in the list of dependencies to install in the github workflow.

Hope that helps!

**Comment by hugofloresgarcia** [comment]
that worked! thanks! :)
