### ISSUE TITLE
Request: add 'includes' file structure to template

### ISSUE THREAD

**Issue by JoseDiazRohena** [sudara/pamplejuce#20]
I spent a lot of time wracking my brain trying to sort how to build my project with source files outside of `~/repo_root/source`. It's actually not very hard at all. 

It would be nice to have something in the template making this more obvious. This could be as simple as a dummy class living in a `~/repo_root/libs/common` folder that is referenced in the audio processor header and making the necessary changes to `CMakeLists.txt`.

**Comment by sudara** [comment]
I'm thinking about adding the melatonin inspector module as an example of a juce module. It would live in `modules/melatonin_inspector` — would that have been helpful? 

What solution did you end up with?

**Comment by JoseDiazRohena** [comment]
I think what would have helped me is something that helped answer the simple question: what if want to use files that are not JUCE modules and not in the main source folder?

It turned out not being a big deal. If I recall correctly I just had to:

- add any files I wanted to use as source files
- change the source tree root to repo root so my `libs` folder would be visible
- add that `libs` folder to the target include dirs for main target and test

Part of me thinks "but this is 101 level stuff". The other part of me thinks "yeah, that's why this is a template". So I guess the real question whether the project is positioned towards rank cmake amateurs or people who just need a little boost getting cmake to work with JUCE.

**Comment by sudara** [comment]
It sounds like it's worth adding comments around the source files / include dirs in the CMakeLists.txt to more clearly explain what's happening and maybe make a mention in the companion blog article https://melatonin.dev/blog/how-to-use-cmake-with-juce/

**Comment by JoseDiazRohena** [comment]
Sounds good
