### ISSUE TITLE
Should the line listed below in the cmake reference the project name rather than PAMPLEJUCE_IPP ?

### ISSUE THREAD

**Issue by 7sharp9** [sudara/pamplejuce#29]
https://github.com/sudara/pamplejuce/blob/8824f49341223043fbccf2dc3953865abacf9659/CMakeLists.txt#L136

**Comment by 7sharp9** [comment]
e.g PROJECT_NAME + _IPP

**Comment by 7sharp9** [comment]
Ah, I see it referenced here:
https://github.com/sudara/pamplejuce/blob/8824f49341223043fbccf2dc3953865abacf9659/Tests/PluginBasics.cpp#L19

Perhaps a generic name rather than the PAMPLEJUCE prefix?

**Comment by sudara** [comment]
Hi there! 

Thanks for the the suggestion and taking the time to share it.

I like the benefit of the name staying the same across multiple projects. JUCE has `JUCE_IPP_AVAILABLE` which is what lead me to name it something differentiated that spoke to its origins.

I guess it's pretty easy to rename for anyone kicking off a new project...

**Comment by 7sharp9** [comment]
It was really just for some consistancy rather than being tied to the template really.  I dont think I got snagged my it as it would only really affect the test projects.   Im sort of inbetween migrating to your template but thanks for doing this its a big help!
