### ISSUE TITLE
How to add juce_generate_juce_header so that #include <JuceHeader.h> can be used in the source files?

### ISSUE THREAD

**Issue by 7sharp9** [sudara/pamplejuce#59]
Im wondering how I would go abaout adding 'juce_generate_juce_header' in the 'CMakeList.txt' so i can add a simple '#include <JuceHeader.h>' in my source files?

Do I add this to the 'SharedCode' or the `"${PROJECT_NAME}"` this pert of the template I do noy fully inderstand yet...

Thanks for any insight!

Dave.

**Comment by 7sharp9** [comment]
I guess its just laziness and unfamiluarity where the juce bits and pieces are located, having them collated in the `JuceHeader.h` was just handy thats all :-)

**Comment by sudara** [comment]
I've never used JuceHeader with CMake, but reading the [docs](https://github.com/juce-framework/JUCE/blob/master/docs/CMake%20API.md#juce_generate_juce_header), you would specify `juce_generate_juce_header(SharedCode)` *after* the `target_link_libraries` line.

That command looks at the added modules to generate the header, so you'll still need to manually figure out what modules you depend on...

Hope that helps!
