### ISSUE TITLE
MacOS deployment target issue

### ISSUE THREAD

**Issue by jacobweber** [sudara/pamplejuce#6]
Thanks for this template -- it's very helpful.

When I ran the Standalone app on Mac OS 10.14.6., I got the error: `You have macOS %@. The application requires macOS %@ or later.` Not sure what's up with the version string there. But adding this to the top of CMakeLists.txt fixed it:
```
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "Minimum OS X deployment version")
```

**Comment by sudara** [comment]
@jacobweber Thanks for this! I'm guilty of not having tried to build the standalone on this repo, I appreciate the contribution.
