### ISSUE TITLE
[Bug?] DMG will not let you copy on MacOS 14.1.1

### ISSUE THREAD

**Issue by mhhollomon** [sudara/pamplejuce#66]
After opening the  downloaded dmg (from release 0.0.1), Dragging the vst3 (or component) over the proper folder results in the icon snapping back to the original position without doing anything.

After using `xattr` to remove the quarantine attribute it works fine.

Using `codesign` I can see that the dmg is signed, notarized, and stapled.

M2 using MacOS 14.1.1

**Comment by sudara** [comment]
Hi there, yes I go into detail about this in the [companion blog article](https://melatonin.dev/blog/how-to-code-sign-and-notarize-macos-audio-plugins-in-ci/#full-ci-example-github-actions), but I'll add something to the readme about this — bottom line is pamplejuce will be eventually moving to .pkg installers. @The-Him is talking about contributing a starting place for this!

**Comment by sudara** [comment]
I had hoped that my technical support incident with Apple prodded them to fix this in Ventura 14.0 (it was working for me again) so this is sort of a bummer. I could contact them again, but ultimately since it's unusable for 13.x, then it's still not pragmatic...

**Comment by sudara** [comment]
Will be superseded by #46
