### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by davens** [sudara/pamplejuce#7]
Hello! Thanks for the great work here - we'd love to start creating plugins using this template you've created.

However, as there is no license file:
"If there’s no license, it means that the code is “All rights reserved” by default. This is really bad because it means that everyone who uses this template to start their own project are doing it illegaly and breaking your copyright. Being the code on GitHub allows everyone to look at it (as per the GitHub’s Terms of Service), but it doesn’t give anyone rights to use the code or fork it."

**Comment by sudara** [comment]
Really strange, not sure how I forgot this, thanks!
