### ISSUE TITLE
Windows Code-Signing Recommendations

### ISSUE THREAD

**Issue by tobiashienzsch** [sudara/pamplejuce#73]
What is your current status when it comes to Windows code signing? I read in your blog that there is a new Azure service, but it is still in preview. I now have to get a Windows certificate and am a bit unsure what to do.

In the blog you say that you had to submit company documents. What does that look like as a self-employed freelancer? Is my VAT ID sufficient?

**Comment by PhilDaThrill** [comment]
There is some new info out on this
https://github.com/koaladsp/KoalaDocs/blob/master/azure-code-signing-for-plugin-developers.md

**Comment by sudara** [comment]
See my reply here: https://forum.juce.com/t/azure-code-signing-for-plugin-developers-guide/60391/14?u=sudara

I'll have a guide out — it should finally be public preview in about a week, maybe a bit more. I definitely recommend going with that over buying a cert and doing it the old manual way. 

Pamplejuce needs be updated to this new tooling as well..

**Comment by sudara** [comment]
Just to close this out: Azure Trusted Signing is my recommendation for businesses with 3+ years of history, [my tutorial is here](https://melatonin.dev/blog/code-signing-on-windows-with-azure-trusted-signing/).
