### ISSUE TITLE
About `*_SharedCode.a` in Linux releases

### ISSUE THREAD

**Issue by zsliu98** [sudara/pamplejuce#80]
Hi! I am not familiar with Linux but recently a Linux user told me the `*_SharedCode.a` in the zip file (Linux release) is not needed at all. It seems that the VST3 is still runnable without that file. I google it and I find the following statement from Anthony:

> .a is a static library, it’s the shared code element. This file is used to link with each of the formats so they contain the same shared code, as it’s linked statically you don’t need to share it with any users - once all your builds are complete it can be disregarded.

May I ask whether it is safe to remove that `*_SharedCode.a`  file from Linux releases?

**Comment by sudara** [comment]
Yes I believe it can be deleted / ignored! We should probably make sure the zip doesn't include it in pamplejuce (you are welcome to submit a PR!, otherwise I'll leave this open!)
