### ISSUE TITLE
I have a problem using the template where error says "file is too big"

### ISSUE THREAD

**Issue by orstphone** [sudara/pamplejuce#83]
I'm trying to import the project files created using Visual Studio on Projucer   but I'm immediately encountering the issue and it says "juce_gui_basics.cpp.obj : file is too big"
I didn't change anything except everything inside /source folders where PluginEditor class and  PluginProcessor class is located and also the CMakeLists.txt where the file is bit edited by following the guideline.
Tried to address this issue but I couldn't find any information regarding this problem.
System is Windows 11, IDE is CLion

**Comment by sudara** [comment]
Did you resolve it? It sounds similar
to an issue seen with minGW — JUCE doesn’t officially support that compiler (worth double
checking which compiler you are using)
