### ISSUE TITLE
Unit Tests Broken since Update to Catch2 v3

### ISSUE THREAD

**Issue by carthach** [sudara/pamplejuce#9]
Thank you very much for this wonderful resource!

It seems unit tests aren't being picked up since [Update to Catch2 v3](https://github.com/sudara/pamplejuce/commit/062e9040e711cc34c5e869a368d5984d7c92127e)

Or am I missing something?

**Comment by sudara** [comment]
@carthach Yikes, just seeing this now, thanks for the heads up!

**Comment by carthach** [comment]
Thank you for fixing!
