### ISSUE TITLE
Error in "Generate Installer" Step on Windows when Plugin Formats do not Include Standalone

### ISSUE THREAD

**Issue by jerryuhoo** [sudara/pamplejuce#94]
## Description:
When attempting to generate the installer on Windows, if the plugin formats do not include the Standalone format, I encounter an error. The error message is as follows:
```
Source file "D:\a\ ... \Release\Standalone\myplugin.exe" does not exist.
```

BTW, is AAX supported on Windows?

**Comment by sudara** [comment]
Where is the error encountered?

If you modify the formats you are building, you'll have to modify the packaging setup too. For windows, that means removing the standalone line from `packaging/installer.iss`

**Comment by jerryuhoo** [comment]
I see, Thank you!
